[[plugins]]
repo = 'dag/vim2hs'
on_ft = ['haskell']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = ['jade']

[[plugins]]
repo = 'gre/play2vim'
on_ft = ['scala']

[[plugins]]
repo = 'mxw/vim-jsx'
on_source = ['vim-javascript']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = ['stylus']
