[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
[[plugins]]
repo = 'haya14busa/incsearch.vim'
[[plugins]]
repo = 'othree/html5.vim'
[[plugins]]
repo = 'rcmdnk/vim-markdown'
[[plugins]]
repo = 'rking/ag.vim'
[[plugins]]
repo = 'vim-scripts/sudo.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimshell'
